<?php

require_once APPPATH . '/models/orm/Relation.php';
/**
 * Created by PhpStorm.
 * User: sandr
 * Date: 22/11/2016
 * Time: 4:45 PM
 */
class AsignaturaCarrera extends Relation
{
    public $anio;
    public $regimen;
    public $Asignatura_id;
    public $Caerrera_id;

    public function get_primary_key_column_name()
    {
        return parent::get_primary_key_column_name(); // TODO: Change the autogenerated stub
    }

    /**
     * Retorna el nombre de la tabla correspondiente a ésta Entity
     * @return string Nombre de la tabla
     */
    public function get_table_name()
    {
        return 'asignatura_carrera';
    }

    /**
     * Retorna un arreglo de string con los nombres de las columnas que no son claves primarias ni foráneas.
     * @return array columnas
     */
    public function get_property_column_names()
    {
        return ['anio', 'regimen'];
    }


    /**
     * Retorna un arreglo de las relaciones uno-a-uno o uno-a-muchos que posee ésta Entity.
     * Cada relación se representa con un arreglo asociativo que contiene las siguientes claves:
     *  - entity_class_name : string Fully qualifiqued Name de la clase entity correspondiente a la entidad destino
     *  - foreign_key_column_name : string El nombre de la columna correspondiente a la clave foránea de esta relación
     *  - property_name : string Nombre de la propiedad en donde colocar el objeto Entity
     * @return array Relaciones a uno-a-uno o muchos-a-uno
     */
    public function get_relations_many_to_one()
    {
        // TODO: Implement get_relations_many_to_one() method.

        $relations[0] =
            [
                'entity_class_name' => 'Asignatura',
                'foreign_key_column_name' => 'id',
                'property_name' => 'Asignatura_id'
            ];
        $relations[1] =
            [
                'entity_class_name' => 'Carrera',
                'foreign_key_column_name' => 'id',
                'property_name' => 'Carrera_id'
            ];


        //return $relations;
    }

    /**
     * @return mixed
     */
    public function get_id()
    {
        // TODO: Implement get_id() method.
    }

    /**
     * Establece las propiedades de la Entity en base al arreglo asociativo recibido.
     * @param array $data
     * @return none
     */
    public function from_row($data)
    {
        if(isset($data['anio'])) $this->anio = $data['anio'];
        if(isset($data['regimen'])) $this->regimen = $data['regomen'];
        if(isset($data['Asignatura_id'])) $this->Asignatura_id = $data['asignatura'];
        if(isset($data['Carrera_id'])) $this->Caerrera_id = $data['Carrera_id'];
        // TODO: Implement from_row() method.
    }

    /**
     * Devuelve un arreglo asociativo con una representación de ésta instancia de la Entity, cuyas claves coinciden
     * con los nombres de las columnas de la tabla a la que corresponde
     * @return array
     */
    public function to_row()
    {
        $data['anio'] = $this->anio;
        $data['regimen'] = $this->regimen;
        $data['Asignatura_id'] = $this->Asignatura_id;
        $data['Carrera_id'] = $this->Carrera_id;
        return $data;
        // TODO: Implement to_row() method.
    }

}